"""
Medical Report Generator
Generates text-based medical reports for VitalLens assessments
"""

from datetime import datetime
import io

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

def generate_medical_report(disease_type, health_data, probability, risk_level, recommendations, lab_tests):
    """
    Generate comprehensive text-based medical report
    
    Args:
        disease_type: Type of disease assessed
        health_data: Dictionary of health parameters
        probability: Prediction probability
        risk_level: Risk level (Low/Moderate/High)
        recommendations: Dictionary of lifestyle recommendations
        lab_tests: List of recommended lab tests
    
    Returns:
        PDF bytes for download
    """
    
    report = {
        'title': 'VitalLens - Multi-Modal Disease Risk Assessment Report',
        'date': datetime.now().strftime('%B %d, %Y'),
        'time': datetime.now().strftime('%I:%M %p'),
        'report_id': f'VL-{datetime.now().strftime("%Y%m%d%H%M%S")}',
        'assessment_type': disease_type.replace('_', ' ').title(),
        'risk_level': risk_level,
        'probability': f'{probability:.1f}%',
        'health_data': health_data or {},
        'recommendations': recommendations or {},
        'lab_tests': lab_tests or [],
        'next_steps': get_next_steps(risk_level, disease_type),
        'disclaimer': (
            'MEDICAL DISCLAIMER: This report is generated by an AI-based risk assessment system '
            'for educational and informational purposes only. It does NOT constitute professional medical '
            'advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified '
            'health provider with any questions regarding a medical condition.'
        )
    }
    
    return _build_report_pdf(report)


def _build_report_pdf(report):
    """Build a simple PDF report and return it as bytes."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4, title=report['title'])
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph(report['title'], styles['Title']))
    story.append(Spacer(1, 12))

    story.append(Paragraph(f"Report ID: {report['report_id']}", styles['Normal']))
    story.append(Paragraph(f"Date: {report['date']}  Time: {report['time']}", styles['Normal']))
    story.append(Paragraph(f"Assessment Type: {report['assessment_type']}", styles['Normal']))
    story.append(Spacer(1, 8))

    story.append(Paragraph(f"Risk Level: {report['risk_level']}", styles['Heading3']))
    story.append(Paragraph(f"Predicted Probability: {report['probability']}", styles['Normal']))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Health Data", styles['Heading3']))
    if report['health_data']:
        for key, value in report['health_data'].items():
            story.append(Paragraph(f"- {key}: {value}", styles['Normal']))
    else:
        story.append(Paragraph("- No structured health data provided.", styles['Normal']))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Lifestyle Recommendations", styles['Heading3']))
    if report['recommendations']:
        for category, items in report['recommendations'].items():
            story.append(Paragraph(f"{category}", styles['Heading4']))
            if items:
                for item in items:
                    story.append(Paragraph(f"- {item}", styles['Normal']))
            else:
                story.append(Paragraph("- No recommendations.", styles['Normal']))
    else:
        story.append(Paragraph("- No recommendations available.", styles['Normal']))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Recommended Lab Tests", styles['Heading3']))
    if report['lab_tests']:
        for test in report['lab_tests']:
            story.append(Paragraph(f"- {test}", styles['Normal']))
    else:
        story.append(Paragraph("- No lab tests available.", styles['Normal']))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Next Steps", styles['Heading3']))
    for step in report['next_steps']:
        story.append(Paragraph(f"- {step}", styles['Normal']))
    story.append(Spacer(1, 12))

    story.append(Paragraph("Medical Disclaimer", styles['Heading3']))
    story.append(Paragraph(report['disclaimer'], styles['Normal']))

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes


def get_next_steps(risk_level, disease_type):
    """
    Get recommended next steps based on risk level
    
    Args:
        risk_level: Risk level (Low/Moderate/High)
        disease_type: Type of disease
    
    Returns:
        List of next steps
    """
    steps = []
    
    if risk_level == "High":
        steps = [
            "Schedule an appointment with a healthcare provider within 1-2 weeks",
            "Get all recommended lab tests completed as soon as possible",
            "Begin implementing lifestyle modifications immediately",
            "Monitor symptoms closely and seek emergency care if symptoms worsen",
            "Bring this report to your medical consultation"
        ]
    elif risk_level == "Moderate":
        steps = [
            "Schedule a medical consultation within 2-4 weeks",
            "Complete recommended lab tests",
            "Start making recommended lifestyle changes",
            "Track your symptoms and health parameters",
            "Follow up with healthcare provider for test results"
        ]
    else:  # Low risk
        steps = [
            "Schedule routine health check-up within 3-6 months",
            "Continue maintaining healthy lifestyle habits",
            "Stay vigilant about preventive health measures",
            "Consider getting recommended screening tests",
            "Monitor any changes in health status"
        ]
    
    # Disease-specific steps
    specialist_map = {
        'diabetes': 'Endocrinologist or Diabetologist',
        'heart_disease': 'Cardiologist',
        'pneumonia': 'Pulmonologist or Infectious Disease Specialist',
        'brain_tumor': 'Neurologist or Neurosurgeon'
    }
    
    if disease_type in specialist_map:
        steps.append(f"Consider consulting a {specialist_map[disease_type]} for specialized care")
    
    return steps

